export type ProductStatus =
  | 'activo' |'stock_bajo' |'sin_stock' |'por_vencer' |'descontinuado';

export interface Product {
  id: string;
  sku: string;
  barcode: string;
  name: string;
  category: string;
  supplier: string;
  quantity: number;
  minStock: number;
  maxStock: number;
  unitCost: number;
  salePrice: number;
  unit: string;
  expiryDate: string;
  status: ProductStatus;
  location: string;
  notes: string;
}

// BACKEND INTEGRATION POINT: GET /api/products
export const initialProducts: Product[] = [
  {
    id: 'product-001',
    sku: 'PRD-0041',
    barcode: '7702001110032',
    name: 'Leche entera 1L Alpina',
    category: 'Lácteos',
    supplier: 'Alpina S.A.',
    quantity: 0,
    minStock: 24,
    maxStock: 120,
    unitCost: 2850,
    salePrice: 3500,
    unit: 'unidad',
    expiryDate: '2026-06-15',
    status: 'sin_stock',
    location: 'Nevera A-1',
    notes: 'Producto de alta rotación',
  },
  {
    id: 'product-002',
    sku: 'PRD-0083',
    barcode: '7702101023411',
    name: 'Aceite vegetal 900ml Premier',
    category: 'Despensa',
    supplier: 'Grasas S.A.',
    quantity: 0,
    minStock: 18,
    maxStock: 80,
    unitCost: 7400,
    salePrice: 9200,
    unit: 'unidad',
    expiryDate: '2027-01-20',
    status: 'sin_stock',
    location: 'Estante B-3',
    notes: '',
  },
  {
    id: 'product-003',
    sku: 'PRD-0019',
    barcode: '7703220045600',
    name: 'Yogur fresa 200g Colanta',
    category: 'Lácteos',
    supplier: 'Colanta Ltda.',
    quantity: 4,
    minStock: 12,
    maxStock: 60,
    unitCost: 1650,
    salePrice: 2100,
    unit: 'unidad',
    expiryDate: '2026-05-22',
    status: 'stock_bajo',
    location: 'Nevera A-2',
    notes: 'Revisar fecha de vencimiento',
  },
  {
    id: 'product-004',
    sku: 'PRD-0057',
    barcode: '7704550089012',
    name: 'Queso doble crema 500g Alpina',
    category: 'Lácteos',
    supplier: 'Alpina S.A.',
    quantity: 20,
    minStock: 10,
    maxStock: 50,
    unitCost: 8900,
    salePrice: 11500,
    unit: 'unidad',
    expiryDate: '2026-05-18',
    status: 'por_vencer',
    location: 'Nevera B-1',
    notes: 'Vence en 8 días',
  },
  {
    id: 'product-005',
    sku: 'PRD-0027',
    barcode: '7701001200145',
    name: 'Arroz Diana 500g',
    category: 'Granos',
    supplier: 'Molinos Diana',
    quantity: 87,
    minStock: 30,
    maxStock: 200,
    unitCost: 1800,
    salePrice: 2400,
    unit: 'unidad',
    expiryDate: '2027-08-30',
    status: 'activo',
    location: 'Estante C-1',
    notes: '',
  },
  {
    id: 'product-006',
    sku: 'PRD-0112',
    barcode: '7891024150055',
    name: 'Jabón de baño Protex 125g',
    category: 'Aseo',
    supplier: 'Colgate-Palmolive',
    quantity: 380,
    minStock: 40,
    maxStock: 200,
    unitCost: 2100,
    salePrice: 2800,
    unit: 'unidad',
    expiryDate: '2028-03-10',
    status: 'activo',
    location: 'Estante D-2',
    notes: 'Exceso de stock — no reordenar',
  },
  {
    id: 'product-007',
    sku: 'PRD-0033',
    barcode: '7411001302000',
    name: 'Gaseosa Coca-Cola 1.5L',
    category: 'Bebidas',
    supplier: 'Coca-Cola FEMSA',
    quantity: 48,
    minStock: 24,
    maxStock: 144,
    unitCost: 3200,
    salePrice: 4200,
    unit: 'unidad',
    expiryDate: '2026-11-05',
    status: 'activo',
    location: 'Nevera C-1',
    notes: '',
  },
  {
    id: 'product-008',
    sku: 'PRD-0064',
    barcode: '7501020403538',
    name: 'Pan tajado Bimbo 500g',
    category: 'Panadería',
    supplier: 'Bimbo de Colombia',
    quantity: 30,
    minStock: 15,
    maxStock: 60,
    unitCost: 4500,
    salePrice: 5800,
    unit: 'unidad',
    expiryDate: '2026-05-16',
    status: 'por_vencer',
    location: 'Estante A-1',
    notes: 'Producto perecedero',
  },
  {
    id: 'product-009',
    sku: 'PRD-0098',
    barcode: '7702230011209',
    name: 'Atún en agua Van Camps 160g',
    category: 'Despensa',
    supplier: 'Van Camps Colombia',
    quantity: 156,
    minStock: 30,
    maxStock: 180,
    unitCost: 2900,
    salePrice: 3800,
    unit: 'unidad',
    expiryDate: '2028-06-20',
    status: 'activo',
    location: 'Estante B-1',
    notes: '',
  },
  {
    id: 'product-010',
    sku: 'PRD-0076',
    barcode: '7706598010047',
    name: 'Detergente líquido Ariel 1.8L',
    category: 'Aseo',
    supplier: 'Procter & Gamble',
    quantity: 9,
    minStock: 15,
    maxStock: 60,
    unitCost: 18500,
    salePrice: 23900,
    unit: 'unidad',
    expiryDate: '2028-01-15',
    status: 'stock_bajo',
    location: 'Estante D-1',
    notes: '',
  },
  {
    id: 'product-011',
    sku: 'PRD-0045',
    barcode: '7702001300016',
    name: 'Mantequilla sin sal 250g Alpina',
    category: 'Lácteos',
    supplier: 'Alpina S.A.',
    quantity: 22,
    minStock: 12,
    maxStock: 48,
    unitCost: 5600,
    salePrice: 7200,
    unit: 'unidad',
    expiryDate: '2026-07-10',
    status: 'activo',
    location: 'Nevera A-3',
    notes: '',
  },
  {
    id: 'product-012',
    sku: 'PRD-0133',
    barcode: '7707017540034',
    name: 'Café molido Sello Rojo 250g',
    category: 'Bebidas',
    supplier: 'Federación Nacional de Cafeteros',
    quantity: 0,
    minStock: 20,
    maxStock: 100,
    unitCost: 6800,
    salePrice: 8900,
    unit: 'unidad',
    expiryDate: '2027-04-22',
    status: 'descontinuado',
    location: 'Estante A-2',
    notes: 'Descontinuado por proveedor',
  },
];

export const categories = [
  'Lácteos',
  'Despensa',
  'Granos',
  'Aseo',
  'Bebidas',
  'Panadería',
  'Carnes',
  'Frutas y Verduras',
  'Snacks',
  'Otros',
];

export const suppliers = [
  'Alpina S.A.',
  'Colanta Ltda.',
  'Grasas S.A.',
  'Molinos Diana',
  'Colgate-Palmolive',
  'Coca-Cola FEMSA',
  'Bimbo de Colombia',
  'Van Camps Colombia',
  'Procter & Gamble',
  'Federación Nacional de Cafeteros',
];

export const units = ['unidad', 'kg', 'litro', 'caja', 'paquete', 'docena'];